CREATE TABLE APPUSER (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CHECKPOINT (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    user_id   INTEGER      NOT NULL AUTO_INCREMENT,
    content VARCHAR(256) NOT NULL,
    created_on DATE NOT NULL,
    PRIMARY KEY (id)
);